#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Analyze image directory layout docs generated by Asterfire-dockerfile-builder.

The dockerfile-builder skill can generate a companion layout document, usually
named image_layout.md / 镜像目录结构说明.md.  This file is treated as the
highest-priority human-readable source for mapping local resources to image
absolute paths before falling back to Dockerfile parsing.
"""

from __future__ import annotations

import argparse
import json
import re
from pathlib import PurePosixPath
from typing import Dict, List

ABS_PATH_RE = re.compile(r"(?<![\w.-])(/[A-Za-z0-9_./+\-]+)")
COPY_COMMENT_RE = re.compile(r"COPY\s+(.+?)\s+(/[A-Za-z0-9_./+\-]+)")
ENV_ASSIGN_RE = re.compile(r"\b([A-Z][A-Z0-9_]*(?:HOME|ROOT|DIR))\s*=\s*(/[A-Za-z0-9_./+\-]+)")
TREE_CHILD_RE = re.compile(r"[├└]──\s+([^/#\s][^/#]*)")

RESOURCE_KEYWORDS = (
    "proteinmpnn",
    "model",
    "models",
    "weights",
    "weight",
    "ckpt",
    "checkpoint",
    "database",
    "db",
    "modelforge",
    "rosetta",
    "rf3",
    "alphafold",
    "boltz",
    "bindcraft",
)


def _path_confidence(path: str, source: str) -> str:
    text = f"{path} {source}".lower()
    if any(k in text for k in RESOURCE_KEYWORDS):
        return "high"
    if path.startswith("/opt/"):
        return "high"
    if path.startswith("/app/") and path != "/app":
        return "medium"
    return "low"


def _is_probable_file(path: str) -> bool:
    suffix = PurePosixPath(path).suffix
    return bool(suffix and suffix not in {".d", ".dir"})


def _root_from_path(path: str) -> str:
    """Convert a concrete absolute path into a likely resource root."""
    p = str(PurePosixPath(path))
    if _is_probable_file(p):
        p = str(PurePosixPath(p).parent)
    parts = PurePosixPath(p).parts
    # Prefer /opt/ProjectName and /app/ProjectName when a deeper file/subdir path appears.
    if len(parts) >= 3 and parts[1] in {"opt", "app"}:
        return "/" + parts[1] + "/" + parts[2]
    return p


def _add_candidate(candidates: List[Dict[str, str]], path: str, source: str, confidence: str | None = None) -> None:
    if not path.startswith("/"):
        return
    root = _root_from_path(path)
    if root in {"/", "/app", "/opt", "/workspace"}:
        return
    candidates.append(
        {
            "path": root,
            "source": source,
            "confidence": confidence or _path_confidence(root, source),
        }
    )


def analyze_image_layout(path: str) -> Dict[str, object]:
    text = open(path, "r", encoding="utf-8", errors="replace").read()
    candidates: List[Dict[str, str]] = []
    copy_mappings: List[Dict[str, str]] = []
    env_roots: Dict[str, str] = {}
    mentioned_paths: List[str] = []

    for m in COPY_COMMENT_RE.finditer(text):
        src = m.group(1).strip().strip("`'")
        dst = m.group(2).strip().strip("`'")
        copy_mappings.append({"source": src, "destination": dst})
        _add_candidate(candidates, dst, f"layout COPY {src} -> {dst}", "high")

    for m in ENV_ASSIGN_RE.finditer(text):
        key, value = m.group(1), m.group(2)
        env_roots[key] = value
        _add_candidate(candidates, value, f"layout ENV {key}", "high")

    for line in text.splitlines():
        for m in ABS_PATH_RE.finditer(line):
            p = m.group(1).rstrip("`.,，。:：;；)）]")
            mentioned_paths.append(p)
            if p.startswith(("/opt/", "/app/")):
                _add_candidate(candidates, p, f"layout mentioned path: {line.strip()}")

    # Deduplicate while preserving first high-quality source. Prefer high over medium/low.
    rank = {"high": 3, "medium": 2, "low": 1}
    best: Dict[str, Dict[str, str]] = {}
    order: List[str] = []
    for item in candidates:
        p = item["path"]
        if p not in best:
            best[p] = item
            order.append(p)
        elif rank.get(item["confidence"], 0) > rank.get(best[p]["confidence"], 0):
            best[p] = item

    return {
        "layout": path,
        "copy_mappings": copy_mappings,
        "env_roots": env_roots,
        "mentioned_paths": sorted(set(mentioned_paths)),
        "candidate_image_roots": [best[p] for p in order],
    }


def main() -> None:
    ap = argparse.ArgumentParser(description="Analyze Asterfire image layout document for image resource paths.")
    ap.add_argument("--layout", required=True, help="Path to image_layout.md / 镜像目录结构说明.md")
    ap.add_argument("--json", action="store_true", help="Print JSON only")
    args = ap.parse_args()

    data = analyze_image_layout(args.layout)
    if args.json:
        print(json.dumps(data, ensure_ascii=False, indent=2))
        return

    print("# 镜像目录结构说明分析")
    print(f"Layout: {data['layout']}")
    print("\n## COPY 映射")
    for item in data["copy_mappings"]:
        print(f"- {item['source']} -> {item['destination']}")
    print("\n## ENV 根目录")
    for k, v in data["env_roots"].items():
        print(f"- {k}={v}")
    print("\n## 候选镜像内资源根目录")
    for item in data["candidate_image_roots"]:
        print(f"- {item['path']}  ({item['confidence']}, {item['source']})")


if __name__ == "__main__":
    main()
